#%RAML 1.0 DataType
type: object
properties:
  user: UserType
  authToken: AuthTokenType
example:
  user:
    firstName: "John"
    lastName: "Doe"
    email: "john.doe@example.com"
    age: 30
    gender: "Male"
  authToken:
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
    tokenType: "Bearer"
    expiresIn: 3600