#%RAML 1.0 DataType
type: object
properties:
  userId: integer
  name: string
  items: Item[]?
  groupId: number
example:
  userId: 1
  name: "Living room"
  groupId: 2
  items:
    - itemId: 101
      name: "Chair"
      price: 150
      amount: 20
      type: "Furniture"
      width: 45
      height: 90
      color: "Black"
      collectionId: 501
    - itemId: 102
      name: "Chair"
      price: 322
      amount: 1
      type: "Furniture"
      width: 45
      height: 90
      color: "Red"
      collectionId: 501