#%RAML 1.0 DataType
type: object
properties:
  invitationId: integer
  groupId: integer
  senderId: integer
  recieverEmail: string
  token: string
  accepted: boolean
  createdAt: datetime
  acceptedAt: datetime
example: 
  invitationId: 1 
  groupId: 2
  senderId: 3
  recieverEmail: "johnDoe@mail.dk"
  token: "sakjdosdifjs834jrf"
  accepted: false
  createdAt: 2015-12-17T00:00:00Z
  acceptedAt: 2015-12-17T00:00:00Z

