#%RAML 1.0 DataType

type: object
properties:
  itemId: integer
  name: string
  price: integer
  amount: integer
  type: string
  width: integer?
  height: integer?
  color: string?
  collectionId: integer
example:
  itemId: 1
  name: "The Egg"
  price: 321
  amount: 2
  type: "Chair"
  width: 120
  height: 80
  color: "blue"
  collectionId: 2